server:
  port : 8002

spring:
  application:
    name: short-link-admin
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.141.1:8848
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      port: 6379
      password: 123456
      host: 8.134.93.74
short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
