server:
  port : 8001

spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      port: 6379
      password: Nruonan996
      host: 129.204.155.72
  rabbitmq:
    host: 129.204.155.72
    username: xzn
    password: Nruonan996
    virtual-host: /
    port: 5672
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: http://8.134.93.74:8858
        port: 8719
    nacos:
      discovery:
        server-addr: 192.168.141.1:8848
#  实现mybatis-plus删除是将del_flag置为1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 59a7038d5ff971437ca36efc2bce8571
  goto-domain:
    white-list:
      enable: true
      names: '知乎,掘金,博客园'
      details:
        - zhihu.com
        - juejin.cn
        - cnblogs.com
#暴露所有的端点
management:
  health:
    rabbit:
      enabled: false